title: Blog di Rocco Scavone
email: r.scavone@tabsrl.com
description: >-
  Blog tecnico di Rocco Scavone con articoli su sviluppo software, 
  tecnologie web e best practices.
baseurl: "/blog"
url: "https://scavone87.github.io"
twitter_username: 
github_username:  scavone87

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
