source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "webrick", "~> 1.8"
gem "jekyll-sass-converter", "~> 2.0"
gem "minima", "~> 2.5"

# Gemme standard che non sono più incluse di default in Ruby 3.4
gem "csv"
gem "base64"
gem "logger"
gem "bigdecimal"

# Specifica la piattaforma per sass-embedded per evitare problemi con aarch64-linux-musl
gem "sass-embedded", platforms: [:ruby, :x64_mingw, :mingw, :mswin]

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17.0"
  gem "jekyll-seo-tag", "~> 2.8.0"
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jekyll-paginate", "~> 1.1.0"
end
