name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job using Docker
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build frontend
      - name: Build frontend with Docker
        run: |
          docker build -t frontend-build ./frontend
          docker create --name frontend-container frontend-build
          mkdir -p _site
          docker cp frontend-container:/app/build/. _site/
          docker rm frontend-container

      # Build blog
      - name: Build blog with Docker
        run: |
          docker build -t blog-build ./blog
          docker create --name blog-container blog-build
          docker start blog-container
          docker exec blog-container bundle exec jekyll build
          mkdir -p _site/blog
          docker cp blog-container:/app/_site/. _site/blog/
          docker rm blog-container

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  # Deploy job
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
